- name: Determine action
  ansible.builtin.set_fact:
    action: "{{ action | default('install') }}"

- name: Download and install OpenShift mirror binaries
  become: true
  block:
    - name: Delete OpenShift mirror and mirror-registry CLI (ensure latest)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "mirror-registry"
        - "oc-mirror"

    - name: Install OpenShift mirror and mirror-registry CLI
      ansible.builtin.unarchive:
        src: "{{ item }}"
        remote_src: yes
        dest: "/usr/local/bin"
        mode: '755'
        exclude:
          - README.md
      when: action == "install"
      loop:
        - "{{ openshift_mirror_cli_url }}"
        - "{{ openshift_mirror_registry_url }}"

- name: Install Quay Registry using mirror-registry CLI
  ansible.builtin.command:
    command: "{{ mirror_registry_cli }} install -v \
          {{ mirror_registry.extra_args }} \
          --quayHostname {{ mirror_registry.hostname }} \
          --quayRoot {{ mirror_registry.quay_root }} \
          --initUser {{ mirror_registry.username }} \
          --initPassword {{ mirror_registry.password }}"
  delegate_to: registry-server
  when: action == "install"

- name: Uninstall Quay Registry using mirror-registry CLI
  ansible.builtin.command:
    command: "{{ mirror_registry_cli }} uninstall -v"
  delegate_to: registry-server
  when: action == "uninstall"
