- ansible.builtin.set_fact:
    action: "{{ action | default('install') }}"
    hostname: "{{ mirror_registry.hostname }}.{{ mirror_registry.domain }}"
    extra_args: "{{ mirror_registry.extra_args | default('') }}"
  delegate_to: registry-server

- name: Ensure latest http modules
  ansible.builtin.pip:
    name:
      - requests
      - urllib3
    state: latest
  delegate_to: registry-server

- name: Download and install OpenShift mirror binaries
  become: true
  become_method: sudo
  delegate_to: registry-server
  block:
    - name: Delete OpenShift mirror and mirror-registry CLI (ensure latest)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ mirror_registry.install_dir }}/mirror-registry"
        - "{{ mirror_registry.install_dir }}/oc-mirror"

    - name: Install OpenShift mirror and mirror-registry CLI
      ansible.builtin.unarchive:
        src: "{{ item }}"
        remote_src: true
        dest: "{{ mirror_registry.install_dir }}"
        mode: '755'
        exclude:
          - README.md
      loop:
        - "{{ openshift_mirror_cli_url }}"
        - "{{ openshift_mirror_registry_url }}"

- name: Restart systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: true
  become: true
  delegate_to: registry-server

- name: Set mirror registry cli
  ansible.builtin.set_fact:
    mr_cli: "{{ mirror_registry.install_dir }}/mirror-registry"

- name: Install Quay Registry using mirror-registry CLI
  ansible.builtin.command:
    cmd: "{{ mr_cli }} install -v \
          {{ extra_args }} \
          --quayHostname {{ hostname }} \
          --quayRoot {{ mirror_registry.quay_root_folder }} \
          --initUser {{ mirror_registry.username }} \
          --initPassword {{ mirror_registry.password }}"
  when: action == "install"
  delegate_to: registry-server

- name: Copy Quay Certs
  ansible.builtin.copy:
    remote_src: true
    src: "/home/{{ mirror_registry.vm_user }}/quay/quay-rootCA/rootCA.pem"
    dest: "/etc/pki/ca-trust/source/anchors/quay-syntaxs.crt"
  become: true
  when: action == "install"
  delegate_to: registry-server

- name: Trust Quay Certs
  ansible.builtin.command:
    cmd: update-ca-trust extract
  become: true
  when: action == "install"
  delegate_to: registry-server

- name: Uninstall Quay Registry using mirror-registry CLI
  ansible.builtin.command:
    cmd: "{{ mr_cli }} uninstall -v"
  when: action == "uninstall"
  delegate_to: registry-server

- name: Remove Quay Cert
  ansible.builtin.file:
    path: "/etc/pki/ca-trust/source/anchors/quay-syntaxs.crt"
    state: absent
  when: action == "uninstall"
  delegate_to: registry-server
