###################################################################
############ PLEASE VERIFY YOU READ INSTRUCTIONS BELOW ############
###################################################################

# 1. Please make sure you set a way to add the DNS record for Mirror Registry
# You can use OpnSense unbound (built in) by setting the
# dns.method: opnsense_unbound


ocp_channel: stable
openshift_version: 4.17
openshift_channel: "{{ ocp_channel }}-{{ openshift_version }}"
mirror_version: 1.3.9

hypervisor:
  type: proxmox
  storage: nvme-1
  proxmox:
    node: pve # the name of the node to install on

dns:
  method: opnsense_unbound
  api_key_file: ~/opnsense_api.conf
  opnsense:
    ip: 192.168.1.1
    port: 445
    ssl_verify: false

mirror_registry:
  POST_SETUP_IP_HOOK: ../../../extras/post_registry_provision.py
  vm_size_gb: 250
  vm_cores: 2
  vm_ram: 8192
  vm_user: quayadmin
  vlan_tag: 0 # keep at 0 if you want default network tagging
  hostname: "quay"
  domain: "syntaxs.io"
  username: quayadmin
  password: "6rD3m9V7ZcAl"
  # extra_args: "--targetUsername {{ mirror_registry.username }}"
  quay_root_folder: ~/quay
  install_dir: "/usr/local/bin"