###################################################################
############ PLEASE VERIFY YOU READ INSTRUCTIONS BELOW ############
###################################################################

# 1. Please make sure you set a way to add the DNS record for Mirror Registry
# You can use OpnSense unbound (built in) by setting the
# dns.method: opnsense_unbound


# 2. Download your pull secret
# https://console.redhat.com/openshift/install/pull-secret
# And enter it under mirror_registry.

# 3. Chose your Mirror Mode:
# Options: 
# - reg2reg | r2r (semi-disconnected)

ocp_channel: stable
openshift_version: 4.18
openshift_channel: "{{ ocp_channel }}-{{ openshift_version }}"
mirror_version: 1.3.9
baremetal_arch: amd64

ocp:
  mirror_mode: r2r
  min_version: 4.18.4
  max_version: 4.18.6

hypervisor:
  type: proxmox
  storage: nvme-1
  proxmox:
    node: pve # the name of the node to install on

dns:
  method: opnsense_unbound
  api_key_file: ~/opnsense_api.conf
  opnsense:
    ip: 192.168.1.1
    port: 445
    ssl_verify: false

mirror_registry:
  POST_SETUP_IP_HOOK: ../../../extras/post_registry_provision.py
  pull_secret_file: ~/pull-secret.txt
  vm_size_gb: 250
  vm_cores: 2
  vm_ram: 12288 # suggest at least 12GB
  vm_user: quayadmin
  vlan_tag: 0 # keep at 0 if you want default network tagging
  hostname: "quay"
  domain: "syntaxs.io"
  username: quayadmin
  password: "6rD3m9V7ZcAl"
  extra_args: "--sslCheckSkip" #"--targetUsername {{ mirror_registry.username }}"
  quay_root_folder: ~/quay
  install_dir: "/usr/local/bin"
