- ansible.builtin.set_fact:
    reg2reg_file: "/home/{{ mirror_registry.vm_user }}/platform_content_r2r.yaml"

- name: Create Platform imageset template
  ansible.builtin.template:
    src: "../../templates/platform_content_r2r.j2"
    dest: "{{ reg2reg_file }}"
  delegate_to: registry-server

- name: Mirror - Registry to Registry (this may take some time)
  ansible.builtin.command:
    cmd: "{{ mirror_registry.install_dir }}/oc-mirror \
      --config={{ reg2reg_file }} \
      docker://{{ mirror_registry.hostname }}.{{ mirror_registry.domain }}:8443"
  delegate_to: registry-server

- name: Find the oc-mirror results folder
  ansible.builtin.find:
    paths: ./oc-mirror-workspace
    patterns: 'results-*'
    file_type: directory
    use_regex: false
  register: mirror_results
  delegate_to: registry-server

- name: Set latest results folder path (sorted by modification time)
  ansible.builtin.set_fact:
    latest_results_path: "{{ (mirror_results.files | sort(attribute='mtime', reverse=true))[0].path }}"

- name: Copy imageContentSourcePolicy.yaml
  ansible.builtin.slurp:
    src: "{{ latest_results_path }}/imageContentSourcePolicy.yaml"
    delegate_to: registry-server
  register: icsp_file

- name: Parse slurped YAML content
  asible.builtin.set_fact:
    image_policy: "{{ slurped_file.content | b64decode | from_yaml }}"

- name: Save to file on host
  ansible.builtin.copy:
    content: image_policy
    dest: "{{ ocp.install_dir }}/iscp.yaml"
    mode: '0755'
