- name: Full OCP Disconnected Install Playbook
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Hypervisor common tasks
      ansible.builtin.include_role:
        name: hypervisor_common

    - name: Download Fedora Server ISO
      ansible.builtin.include_role:
        name: download_fedora_iso
      vars: 
        download_fedora_iso_deploy_on: "{{ deploy_on }}"

    - name: Set the DNS host for the Mirror Registry
      ansible.builtin.include_role:
        name: add_dns
      when: "{{ dns.method is defined }}"

    - name: Install the Mirror Registry on the Server
      ansible.builtin.include_role:
        name: setup_mirror_registry

    - name: Setup Pull Secret and Local Registry
      ansible.builtin.import_role:
        name: setup_pull_secret

    - name: Start the Mirror Content Process 
      ansible.builtin.import_role:
        name: mirror_content
