- name: Find the oc-mirror results folder
  ansible.builtin.find:
    paths: ./oc-mirror-workspace
    patterns: "results-*"
    file_type: directory
    use_regex: false
  register: mirror_results
  delegate_to: registry-server

- name: Set latest results folder path (sorted by modification time)
  ansible.builtin.set_fact:
    latest_results_path: "{{ (mirror_results.files | sort(attribute='mtime', reverse=true))[0].path }}"

- name: Copy imageContentSourcePolicy.yaml
  ansible.builtin.slurp:
    src: "{{ latest_results_path }}/imageContentSourcePolicy.yaml"
  delegate_to: registry-server
  register: icsp_file

- name: Parse slurped YAML content
  ansible.builtin.set_fact:
    image_policy: "{{ icsp_file.content | b64decode | from_yaml }}"

- name: Save to file on host
  ansible.builtin.copy:
    content: "{{ image_policy | to_nice_yaml }}"
    dest: "{{ ocp.install_dir }}/iscp.yaml"
    mode: "0755"
